/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseCard: typeof import('./.vitepress/theme/components/BaseCard.vue')['default']
    HelloWorld: typeof import('./.vitepress/theme/components/HelloWorld.vue')['default']
    ICarbonSun: typeof import('~icons/carbon/sun')['default']
    IMyIconsLogo: typeof import('~icons/my-icons/logo')['default']
  }
}
